[package]
name = "timer_core"
description = "Simple countdown terminal alarm"
version = "0.1.0"
edition = "2021"

[lib]
name = "timer_core"
path = "src/lib.rs"

[[bin]]
name = "timer"
path = "src/main.rs"

[dependencies]
clap = "3.0.0-beta.5"
crossterm = "0.22.1"
glob = "0.3"
regex = "1.5"
rodio = {version = "0.14", features = ["vorbis"]}
signal-hook = "0.3"
time = {version = "0.3.5", features = ["formatting", "local-offset", "parsing"]}

# beep
libc = "0.2"
nix = "0.20"
lazy_static = "1.0"

[dev-dependencies]
time = {version = "0.3.5", features = ["macros"]}

[dev-dependencies.cargo-husky]
version = "1"
default-features = false # Disable features which are enabled by default
features = ["user-hooks"]
